// services/meshNetwork.ts
// Lógica de Integración Meshtastic P2P (Web Serial API)

export interface MeshNode {
  num: string; // ID of the node in Meshtastic (decimal or hex)
  shortName: string;
  longName: string;
  lastHeard: number; // Timestamp
  snr?: number; // Signal to Noise Ratio
  distance?: number; // Est. distance if GPS available
}

export type MeshConnectionState = 'disconnected' | 'connecting' | 'connected' | 'error';

class MeshNetworkManager {
  private port: SerialPort | null = null;
  private reader: ReadableStreamDefaultReader | null = null;
  private nodes: Map<string, MeshNode> = new Map();
  private listeners: ((nodes: MeshNode[]) => void)[] = [];
  public state: MeshConnectionState = 'disconnected';
  private stateListeners: ((state: MeshConnectionState) => void)[] = [];

  // Emit state changes
  private setState(newState: MeshConnectionState) {
    this.state = newState;
    this.stateListeners.forEach(fn => fn(this.state));
  }

  public onStateChange(listener: (state: MeshConnectionState) => void) {
    this.stateListeners.push(listener);
    return () => {
      this.stateListeners = this.stateListeners.filter(l => l !== listener);
    };
  }

  public onNodesUpdate(listener: (nodes: MeshNode[]) => void) {
    this.listeners.push(listener);
    return () => {
      this.listeners = this.listeners.filter(l => l !== listener);
    };
  }

  private notifyListeners() {
    const nodesArray = Array.from(this.nodes.values());
    this.listeners.forEach(fn => fn(nodesArray));
  }

  /**
   * Prompts user to select a Serial device (Meshtastic node)
   */
  public async connect() {
    if (!('serial' in navigator)) {
      console.error("Web Serial API no soportada en este navegador.");
      this.setState('error');
      return;
    }

    try {
      this.setState('connecting');
      // Pide al usuario seleccionar la antena
      this.port = await navigator.serial.requestPort({
        filters: [
          { usbVendorId: 0x10c4 }, // Silabs (e.g. CP210x, LILYGO T-Beam)
          { usbVendorId: 0x1a86 }  // CH340 (e.g. Heltec)
        ]
      });

      await this.port.open({ baudRate: 115200 });
      this.setState('connected');
      this.startReading();
    } catch (err) {
      console.error("Error conectando al nodo Meshtastic:", err);
      this.setState('error');
    }
  }

  public async disconnect() {
    if (this.reader) {
      await this.reader.cancel();
    }
    if (this.port) {
      await this.port.close();
    }
    this.port = null;
    this.setState('disconnected');
    this.nodes.clear();
    this.notifyListeners();
  }

  /**
   * Reads data from the Meshtastic serial port.
   * In a complete implementation, this parses the Protobuf streams generated by the node.
   * Here we implement a simplified parser for demonstration and integration.
   */
  private async startReading() {
    if (!this.port) return;

    // Decodificador de texto para simplificar (Mesh envia logs si no está en modo cliente API puro, 
    // pero para datos P2P precisos usaríamos protobuf. Aquí simulamos la capa lógica superior)
    const textDecoder = new TextDecoderStream();
    const readableStreamClosed = this.port.readable.pipeTo(textDecoder.writable);
    this.reader = textDecoder.readable.getReader();

    try {
      while (true) {
        const { value, done } = await this.reader.read();
        if (done) break;
        
        // Simulating the decoding of a NodeInfo protobuf or log output from Meshtastic
        this.processIncomingData(value);
      }
    } catch (error) {
      console.error("Error leyendo puerto serial:", error);
      this.setState('error');
    } finally {
      this.reader.releaseLock();
    }
  }

  private buffer = '';
  private processIncomingData(data: string) {
    this.buffer += data;
    const lines = this.buffer.split('\n');
    this.buffer = lines.pop() || '';

    lines.forEach(line => {
      // Mock logic: detect NodeInfo broadcasts
      // Ex: "NODE_INFO: id=!1234abcd name=QuantumUser snr=4.5"
      if (line.includes("NODE_INFO") || line.includes("NodeInfo")) {
        // En la implementación real usaríamos protobufjs decodificando paquetes ToRadio/FromRadio
        const nodeIdMatch = line.match(/id=([^\s]+)/);
        const nameMatch = line.match(/name=([^\s]+)/);
        const snrMatch = line.match(/snr=([-\d.]+)/);

        if (nodeIdMatch) {
          const id = nodeIdMatch[1];
          const name = nameMatch ? nameMatch[1] : 'Unknown Node';
          const snr = snrMatch ? parseFloat(snrMatch[1]) : 0;

          this.nodes.set(id, {
            num: id,
            shortName: name.substring(0, 4),
            longName: name,
            lastHeard: Date.now(),
            snr
          });
          this.notifyListeners();
        }
      }
    });
  }

  // Inject a mock node for testing without hardware
  public addMockNode(node: MeshNode) {
    this.nodes.set(node.num, node);
    this.notifyListeners();
  }
}

export const meshNetwork = new MeshNetworkManager();
